FROM envoyproxy/envoy-dev:817cfee4b1188d4e6ce57b2ab0964c317b36130f
COPY todoapp-be/envoy.yaml /etc/envoy/envoy.yaml
EXPOSE 8080
RUN chmod go+r /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml