FROM candlecorp/wasmflow-builder:latest as build

WORKDIR /usr/src/todoapp
COPY todoapp-be/. .
RUN make


FROM phusion/baseimage:master

COPY --from=build  /usr/local/bin/wasmflow /usr/local/bin/wasmflow
COPY --from=build  /usr/local/bin/wafl /usr/local/bin/wafl

WORKDIR /usr/src/todoapp

COPY --from=build /usr/src/todoapp/build/todo.signed.wasm ./build/todo.signed.wasm
COPY --from=build /usr/src/todoapp/todos.wafl ./todos.wafl

ENV PWD=/usr/src/todoapp

EXPOSE 8060

CMD [ "wasmflow", "serve", "/usr/src/todoapp/todos.wafl", "--rpc" , "--rpc-port" , "8060", "--rpc-address", "0.0.0.0"]